### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by TheTonttu** [ProjectBots/StreamRaiderBot#3]
First of all cool project you got here. 😄 

At the moment it is not very straightforward to build the project due to missing dependencies, which seem to point to some absolute directory path outside the repository. It would be nice if there were instructions on how to set up the dev environment. Preferably the external dependencies would be included in the repository directly or through some dependency manager, e.g. Gradle or Maven.

Reason I bring this up is because I was not sure if the release from last month is still compatible with the latest version of Stream Raiders. Also the release is missing the new features and fixes you have added recently. Or were you planning to release a new version soon?

**Comment by ProjectBots** [comment]
thanks for the feedback :) . Im relatively new to github, so i dont know how to add the dependencies to the repo clone option, but i added them in a zip folder on release site. (the native libary used for jcef reaches the file size limit for github)

theoretically the maven dependencies are:
httpclient:
<dependency>
  <groupId>org.apache.httpcomponents</groupId>
  <artifactId>httpclient</artifactId>
  <version>4.5.13</version>
</dependency>

gson:
<dependency>
  <groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>2.8.6</version>
</dependency>

but for jcef i used the win release (its in the bin folder):
https://github.com/jcefbuild/jcefbuild/releases

im open for help 


oh, and i updated the release. Its now up to date

**Comment by TheTonttu** [comment]
Thanks!

It has been 10+ years since I have dabbled in Java and I have never used Maven (or Gradle) before but I will see if I can get something working. Be ready to clean up the mess. 😉

**Comment by ProjectBots** [comment]
im ready 😄
