### ISSUE TITLE
Guide for we use/install

### ISSUE THREAD

**Issue by JoaoAlmirante** [ProjectBots/StreamRaiderBot#5]
Hello,

Can you tell to everyone who want to use this program how can we install/configure the bot for use?
I have trying a lot ways and always get an error.

**Comment by ProjectBots** [comment]
which error?

**Comment by JoaoAlmirante** [comment]
The problem is. v3 dont have any executable.

**Comment by ProjectBots** [comment]
If you dont have the file StreamRaiderBot.jar, please download the release again (the .zip).
Unzip
hit StreamRaiderBot.jar
