### ISSUE TITLE
Feature Request: Specify Priority Streamers

### ISSUE THREAD

**Issue by Enzemo** [ProjectBots/StreamRaiderBot#6]
Hi,

Is there a way that we could "lock" in streamers that we don't want the bot to change away from, regardless of the potential reward?

A lot of the time I simply want to support my friends; I don't care about the rewards and scrolls and gold and such. 

If this could be added it would be much appreciated! I often set it up manually on my preferred streamers and it changes the targets after a couple of campaigns.

**Comment by ProjectBots** [comment]
i added a function to lock a streamer (prevent from be changed). A priority list (automatically switch to a streamer when he/she is playing) will be added in the future.

**Comment by Enzemo** [comment]
Thanks very much :)
