### ISSUE TITLE
Issue: Average income per hour statistics don't update

### ISSUE THREAD

**Issue by Enzemo** [ProjectBots/StreamRaiderBot#7]
Statistics remain at default, rewards continue to track correctly. The below is after 12 hours.

chests:  
-   
basic:  
-   
skins (rare but possible):  
-   
scrolls:  
- 
(tested for 0 hours and 0 minutes)

**Comment by ProjectBots** [comment]
it updates the stats when stopping the bot, but i implemented an manual update (and reset) in the last commit (v3.2.0)
